services:
  mongo:
    container_name: notesdb
    restart: always
    image: mongo:4.2.0
    ports:
      - "27017:27017"
#   expose:
#     - 27017
    volumes:
      - notes_db:/data/db
#    MONGO_INITDB_ROOT_USERNAME: me
#    MONGO_INITDB_ROOT_PASSWORD: password
    networks:
      - express-mongo

networks:
  express-mongo:
  react-express:

volumes:
  notes_db:

